### ISSUE TITLE
[ui] Выбор региона и участка

### ISSUE THREAD

**Issue by schitaytesami** [schitaytesami/schitaytesami.live#1]
На вкладке "#/task" (в index.html) надо добавить у каждого задания три дропдаун-листа:
1. Выборы
2. Регион
3. Участок

В каждом дропдаун-листе по умолчанию должна быть выбрана опция "Автоматический выбор".

Эти три дропдаун-листа должны быть выполнены как Vue-компонент, информация о дереве выборов-регионов-участков должна быть инициализирована при чтении "/stats".

В серверном коде нужно модифицировать "/stats", чтобы он отдавал дерево выборов-регионов-участков. (это можно сделать просто агрегацией по всем Station) - сначала можно из stats_get вернуть заглушку и зафиксировать модель данных.

В рамках этой задачи, пока выбор выборов-региона-участка не на что не влияет.

**Comment by vadimkantorov** [comment]
Пара примеров, как это сделать в vuejs:
https://codepen.io/adnanshussain/pen/KqVxXL/

https://vuejs.org/v2/examples/tree-view.html

**Comment by vadimkantorov** [comment]
Бонус - к дробдаун-листам приделать текстовое поле с фильтром. Фильтр можно реализовать просто как css-selector?

**Comment by vadimkantorov** [comment]
### По интерфейсу
"нужно сделать правки:
1. заголовки "выборы", "регион", "участок" нужно сместить на строчку ниже (чтобы на одной строчке с дропдауном были - компактнее будет)
2. заголовок "фильтр" - нужно замёрджить в placeholder в поле для фильтра

я пока закомиттил туда v-if="false" вместо v-if="$root.user" (можешь для дебага ставить v-if="true" временно)"

### Перенести заглушку с данными в stats_get в питоне
